---

# Homebrew
homebrew_upgrade_all_packages: true
homebrew_installed_packages:
  - git
  - zsh
  - iperf
  - tmux
  - wget
  - tree
  - wakeonlan
  - antigen
  - minicom
  - pass
  - pwgen
  - bat
  - prettyping
  - diff-so-fancy
  - noti
  - telnet
  - tio
  - git-extras
  - git-flow
  - kubernetes-cli
  - kustomize
  - mqtt-cli
  - poetry
  - watch
homebrew_cask_apps:
  - font-jetbrains-mono
  - iterm2
  - spotify
  - balenaetcher
  - nextcloud
  - gpg-suite-no-mail
  - visual-studio-code
  - caffeine
  - viscosity
  - monitorcontrol
  - firefox
  - google-chrome
  - keepassxc
  - mattermost
  - vlc
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - hivemq/mqtt-cli

# Mac App Store (MAS)
mas_signin_dialog: false
mas_upgrade_all_apps: true
mas_installed_apps:
  - id: 1295203466
    name: "Microsoft Remote Desktop"
  - id: 1440147259
    name: "AdGuard for Safari"
  - id: 409201541
    name: Pages
  - id: 409183694
    name: Keynote
  - id: 409203825
    name: Numbers
mas_uninstalled_apps:
  - id: 40891434
    name: iMovie
  - id: 682658836
    name: GarageBand
