---
mas_signin_dialog: false
mas_installed_apps:
      - id: 866773894
        name: "Quiver"
      - id: 419330170
        name: "Moom"
      - id: 1451685025
        name: "WireGuard"
      - id: 1035236694
        name: "Commander One - file manager"
      - id: 497799835
        name: "Xcode"
