os: osx
osx_image: xcode9.3

before_install:
  - brew upgrade openssl || brew install openssl || true
  - brew upgrade python || brew install python || true

script:
  - travis_wait 30 $(PWD)/run.sh --skip-tags mas,virtualbox
