---
# Configure your freshly installed software
- hosts: all
  roles: 
    - role: alphahydrae.vscode
      vscode_extensions:
        - nonoroazoro.syncing
        - platformio.platformio-ide
        - openhab.openhab
        - vscoss.vscode-ansible
      vscode_homebrew_user: "{{ ansible_user_id }}"
  post_tasks:
    - file: src={{playbook_dir}}/dotfiles/zshrc dest=/Users/{{ ansible_user_id }}/.zshrc state=link force=yes
    - file: src={{playbook_dir}}/dotfiles/functions dest=/Users/{{ ansible_user_id }}/.functions state=link force=yes
    - file: src={{playbook_dir}}/dotfiles/gpg.conf dest=/Users/{{ ansible_user_id }}/.gnupg/gpg.conf state=link force=yes
    - file: src={{playbook_dir}}/dotfiles/gpg-agent.conf dest=/Users/{{ ansible_user_id }}/.gnupg/gpg-agent.conf state=link force=yes
    - file: src={{playbook_dir}}/dotfiles/sshcontrol dest=/Users/{{ ansible_user_id }}/.gnupg/sshcontrol state=link force=yes
    - file: src={{playbook_dir}}/dotfiles/gitconfig dest=/Users/{{ ansible_user_id }}/.gitconfig state=link force=yes
    - file: src={{playbook_dir}}/dotfiles/gitignore dest=/Users/{{ ansible_user_id }}/.gitignore state=link force=yes
    - file: src={{playbook_dir}}/dotfiles/.vimrc dest=/Users/{{ ansible_user_id }}/.vimrc state=link force=yes
    - file: src={{playbook_dir}}/dotfiles/editorconfig dest=/Users/{{ ansible_user_id }}/.editorconfig state=link force=yes
    - file: src={{playbook_dir}}/dotfiles/assh.yaml dest=/Users/{{ ansible_user_id }}/.ssh/assh.yml state=link force=yes
    - shell: vim +PluginInstall +qall
    - shell: vim +PluginUpdate +qall
    - shell: assh config build > ~/.ssh/config
    - file: src={{playbook_dir}}/dotfiles/aliases dest=/Users/{{ ansible_user_id }}/.aliases state=link force=yes
    - lineinfile: path=/etc/shells state=present line=/usr/local/bin/zsh
      become: true
    - user: name={{ ansible_user_id }} shell=/usr/local/bin/zsh
      become: true

- hosts: pc
  post_tasks:
    - shell: if [ ! -f /Library/Keyboard Layouts/pc_tastatur.keylayout ]; then sudo cp files/pc_tastatur.keylayout "/Library/Keyboard Layouts/";fi
