---
# Here we describe every software we may want to install
- hosts: all
  roles:
  - role: geerlingguy.homebrew
    tags: brew
  - role: geerlingguy.mas
    tags: mas
  post_tasks:
    - git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: /Users/{{ ansible_user_id }}/.vim/bundle/Vundle.vim
    - shell: hash vim 2> /dev/null && vim +PlugInstall +qall
